Fixed compile error for lttng-modules
This error was caused by missing kernel configs for lttng-modules.

error logs are :

| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c: In function 'lttng_tracepoint_coming':
| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c:227:36: error: 'struct module' has no member named 'num_tracepoints'
|   227 |         for (i = 0; i < tp_mod->mod->num_tracepoints; i++) {
|       |                                    ^~
| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c:232:61: error: 'struct module' has no member named 'tracepoints_ptrs'
|   232 |                 tp = lttng_tracepoint_ptr_deref(&tp_mod->mod->tracepoints_ptrs[i]);
|       |                                                             ^~
| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c: In function 'lttng_tracepoint_going':
| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c:268:36: error: 'struct module' has no member named 'num_tracepoints'
|   268 |         for (i = 0; i < tp_mod->mod->num_tracepoints; i++) {
|       |                                    ^~
| /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.c:273:61: error: 'struct module' has no member named 'tracepoints_ptrs'
|   273 |                 tp = lttng_tracepoint_ptr_deref(&tp_mod->mod->tracepoints_ptrs[i]);
|       |                                                             ^~
| make[4]: *** [/home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work-shared/orange-pi-lite2/kernel-source/scripts/Makefile.build:243: /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src/lttng-tracepoint.o] Error 1
| make[4]: *** Waiting for unfinished jobs....
| make[3]: *** [/home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work-shared/orange-pi-lite2/kernel-source/Makefile:1921: /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/lttng-modules-2.13.12/src] Error 2
| make[2]: Leaving directory '/home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work-shared/orange-pi-lite2/kernel-build-artifacts'
| make[2]: *** [/home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work-shared/orange-pi-lite2/kernel-source/Makefile:234: __sub-make] Error 2
| make[1]: Leaving directory '/home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work-shared/orange-pi-lite2/kernel-source'
| make[1]: *** [Makefile:234: __sub-make] Error 2
| make: *** [Makefile:31: modules] Error 2
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
ERROR: Task (/home/bchoi/orangepi-yocto-bsp/layers/openembedded-core/meta/recipes-kernel/lttng/lttng-modules_2.13.12.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 8172 tasks of which 6304 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/bchoi/orangepi-yocto-bsp/layers/openembedded-core/meta/recipes-kernel/lttng/lttng-modules_2.13.12.bb:do_compile
    log: /home/bchoi/orangepi-yocto-bsp/bchoi-orangepi-lite2_build/tmp/work/orange_pi_lite2-oe-linux/lttng-modules/2.13.12/temp/log.do_compile.2903333
Summary: There were 2 ERROR messages, returning a non-zero exit code.
bchoi@ubuntu-22:~/orangepi-yocto-bsp/bchoi-orangepi-lite2_build$

Signed-off-by: Mark Choi <afewgoodman.choi@gmail.com>